name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: actions/gha-workflows/.gitea/workflows/ci-python-unified.yml@main
    with:
      package-manager: uv
      python-version: '3.14'
      docker-enabled: true
      sonarqube: false
      security-scan: true
