name: Validate PR Title
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: https://git.tainton.uk/actions/conventional-commits-check-action@v1.2.4
        with:
          commit-message: ${{ gitea.event.pull_request.title }}
