name: Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 0"

jobs:
  tag:
    name: Tag release
    uses: https://git.tainton.uk/actions/gha-workflows/.gitea/workflows/release-with-tag.yaml@main

  create_release:
    name: Create Release
    needs: tag
    uses: actions/gha-workflows/.gitea/workflows/create-release-preexisting-tag.yaml@main
    with:
      tag: ${{ needs.tag.outputs.tag_name }}
      body: ${{ needs.tag.outputs.changelog }}
    secrets:
      ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

  create_docker:
    name: Publish Docker Images
    needs: [tag, create_release]
    uses: actions/gha-workflows/.gitea/workflows/build-push-docker.yml@main
    with:
      release: ${{ needs.tag.outputs.tag_name }}
      registry: ${{ vars.PACKAGES_REGISTRY_URL }}
      actions_username: ${{ vars.ACTIONS_USERNAME }}
      ghcr_username: ${{ vars.GHCR_USERNAME }}
    secrets:
      ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
