name: Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 0"

jobs:
  tag:
    name: Tag release
    uses: https://git.tainton.uk/actions/gha-workflows/.gitea/workflows/release-with-tag.yaml@main

  create_release:
    name: Create Release
    needs: tag
    uses: actions/gha-workflows/.gitea/workflows/create-release-preexisting-tag.yaml@main
    with:
      tag: ${{ needs.tag.outputs.tag_name }}
      body: ${{ needs.tag.outputs.changelog }}
    secrets:
      ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

  print_release:
    name: Print Release
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - run: echo "Created release ${{ needs.tag.outputs.tag_name }}."
