version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
  ".github/workflows/**",
  ".gitignore",
  "CODEOWNERS",
  "LICENSE.md",
  "README.md",
  "codecov.yml",
  "renovate.json",
  "requirements-dev.txt",
  "requirements.txt"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "black"
enabled = true
