name: CI
on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'renovate.json'

jobs:
  # analyze:
  #   name: Analyze
  #   runs-on: ubuntu-latest
  #   permissions:
  #     actions: read
  #     contents: read
  #     security-events: write
  #   strategy:
  #     fail-fast: false
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #     - name: Initialize CodeQL
  #       uses: github/codeql-action/init@v2
  #       with:
  #         languages: python
  #     - name: Autobuild
  #       uses: github/codeql-action/autobuild@v2
  #     - name: Perform CodeQL Analysis
  #       uses: github/codeql-action/analyze@v2

  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt && pip install -r requirements-dev.txt
      - name: Lint
        run: pylint --recursive=yes .
      - name: Run test suite
        run: |
          coverage run -m py.test -v
          coverage xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
      - name: Upload Coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: python
          coverage-file: coverage.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
