


name: Test
on:
  push:
    branches: main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Lint Action
        uses: wearerequired/lint-action@v1.12.0

name: Test
on: [push, pull-request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Lint
        continue-on-error: true
        run: pylint PwnedPW.py
      
      - name: Run test suite
        run: pytest
